### ISSUE TITLE
the project can't compile and start normally!

### ISSUE THREAD

**Issue by theseusyang** [vaanxy/ng-container-terminal#1]
when compiling using angular cli , the error is 

ERROR in src/app/app.component.ts(3,40): error TS2307: Cannot find module 'ng-container-terminal'.
src/app/app.component.ts(4,31): error TS2307: Cannot find module 'projects/ng-container-terminal/mock'.
src/app/app.module.ts(5,63): error TS2307: Cannot find module 'ng-container-terminal'.
src/app/app.module.ts(6,31): error TS2307: Cannot find module 'ng-container-terminal/mock'.

**Comment by vaanxy** [comment]
@theseusyang 
this project is designed as an Angular library, so you should build the library first use following command:
`npm run build`
then use `ng serve` to start the demo server
